import time
from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("https://practice.automationtesting.in/")
time.sleep(3)
driver.execute_script("window.scrollBy(0, 600);")
time.sleep(5)
ruby = driver.find_element_by_id('text-22-sub_row_1-0-2-0-0')
ruby.click()
time.sleep(3)
driver.execute_script("window.scrollBy(0, 600);")
time.sleep(3)
reviews = driver.find_element_by_class_name('reviews_tab')
reviews.click()
time.sleep(3)
five_stars_class =  driver.find_element_by_class_name('star-5')
five_stars_class.click()
time.sleep(3)
comment = driver.find_element_by_id('comment')
comment.send_keys('Nice book!')
time.sleep(3)
name = driver.find_element_by_id('author')
name.send_keys('Olga')
time.sleep(3)
email = driver.find_element_by_id('email')
email.send_keys('Olalazareva@gmail.com')
time.sleep(3)
submit = driver.find_element_by_id('submit')
submit.click()
driver.quit()